### ISSUE TITLE
Filter for Multiple Categories

### ISSUE THREAD

**Issue by freinhard** [seantis/seantis.dir.eventsportlet#7]
Allow filtering for multiple categories.

**Comment by msom** [comment]
See also https://github.com/seantis/seantis.dir.base/issues/22

**Comment by msom** [comment]
This is not as trivial as it seems due to the limited possibilities for querying the catalog and the usage of only one index field (categories), see https://github.com/seantis/seantis.dir.events/blob/master/seantis/dir/events/catalog.py#L638.

**Comment by msom** [comment]
We could use TextIndexNG3.
